apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesok
  namespace: default
  labels:
    team: flex
spec:
  image: {{ image }}:{{ tag }}
  port: 8080
  ingresses:
    - "https://nysykepengesoknad.nais.oera-q.local/"
    - "https://tjenester-q1.nav.no/nysykepengesoknad"
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
