apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykepengesok
  namespace: default
  labels:
    team: flex
spec:
  image: {{ image }}:{{ tag }}
  port: 8080
  ingresses:
    - "https://nysykepengesoknad.nais.oera-q.local/"
    - "https://tjenester-q1.nav.no/nysykepengesoknad"
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYFOAPI_ROOT
      value: "https://syfoapi-q.nav.no"
    - name: SYFOREST_ROOT
      value: "https://tjenester-q1.nav.no/syforest"
    - name: LOGINSERVICE_URL
      value: "https://loginservice-q.nav.no/login"
    - name: UNLEASH_URL
      value: "https://tjenester-q1.nav.no/syfounleash"

